import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Apie šią programą",
    AboutThisAppDescription: "Arba pateikite mums atsiliepimų",
    AffiliationsTitle: "Priklausymai",
    Brackets: "({0})",
    CharacterApprentice: "Mokinys",
    CharacterApprentices: "Pameistriai",
    CharacterChild: "Vaikas",
    CharacterChildren: "Vaikai",
    CharacterMate: "Mate",
    CharacterMates: "Bičiuliai",
    CharacterMentor: "Mentorius",
    CharacterMentors: "Mentoriai",
    CharacterParent: "Tėvas",
    CharacterParents: "Tėvai",
    ContributeToTheDataSource: "Prisidėkite prie duomenų šaltinio",
    DurationMoon: "mėnulis",
    DurationMoons: "mėnuliai",
    DurationYear: "metų",
    DurationYears: "metų",
    EmbedAppMenu: "Spustelėkite, jei norite pamatyti daugiau veiksmų",
    EmbedPoweredBy1: "Naudojama {0}",
    EntityNotFound1: "Daugiau informacijos apie subjektą nėra: {0}.",
    EntityProfileTitle: "Subjekto profilis",
    EntitySearchBoxPlaceholder: "Ieškoti katės",
    FamilyTreeTitle: "Šeimos medis",
    FamilyTreeTitle1: "{0} šeimos medis",
    GoToEntityDataSource: "Eikite į šio subjekto duomenų šaltinį.",
    HoweverCheckout1: "Tačiau galite patikrinti, ar {0} yra kažkas.",
    InitializationDescription: "Laikykite tvirtai. Mes vis dar įkeliame kai kuriuos duomenis.",
    InitializationTitle: "Inicijuojama…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Trūksta laiko juostos informacijos.",
    More: "Daugiau",
    NamesTitle: "Vardai",
    NoFamilyTreeInformation: "Nėra šeimos medžio informacijos.",
    OpenInNewWindow: "Atidaryti naujame lange",
    PageNeedsEntityId: "Šiam puslapiui reikia subjekto ID kaip parametro.",
    PositionsHeldTitle: "Laikomos pareigos",
    RelationsTitle: "Santykiai",
    SiteLinksTitle: "Svetainių nuorodos",
    StarTheRepo: "Pridėti saugyklą žvaigždute",
    SwitchLanguage: "Perjungti kalbą",
    TimelineUntilNow: "Dabar",
    UnknownValue: "Nežinoma",
    WelcomeDescription: "Tai <i>Warriors</i> serijos automatinis šeimos medis, dar nebaigtas gaminti. Toliau esančiame paieškos laukelyje įveskite ką nors. <br /> Pvz. įveskite <b>Firestar </b> ir paspauskite enter.",
    WelcomeTitle: "Sveiki",
};

export default prompts;
