import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Over deze app",
    AboutThisAppDescription: "Of geef ons feedback",
    AffiliationsTitle: "voorkeuren",
    Brackets: "({0})",
    CharacterApprentice: "Leerling",
    CharacterApprentices: "leerlingen",
    CharacterChild: "Kind",
    CharacterChildren: "Kinderen",
    CharacterMate: "stuurman",
    CharacterMates: "mates",
    CharacterMentor: "Mentor",
    CharacterMentors: "mentoren",
    CharacterParent: "Ouder",
    CharacterParents: "Ouders",
    ContributeToTheDataSource: "Draag bij aan de gegevensbron",
    DurationMoon: "maan",
    DurationMoons: "manen",
    DurationYear: "jaar",
    DurationYears: "jaar",
    EmbedAppMenu: "Klik om meer acties te zien",
    EmbedPoweredBy1: "Mogelijk gemaakt door {0}",
    EntityNotFound1: "Geen informatie meer beschikbaar voor de entiteit: {0}.",
    EntityProfileTitle: "Entiteitsprofiel",
    EntitySearchBoxPlaceholder: "Zoek naar een kat…",
    FamilyTreeTitle: "Stamboom",
    FamilyTreeTitle1: "Stamboom van {0}",
    GoToEntityDataSource: "Ga naar de gegevensbron van deze entiteit.",
    HoweverCheckout1: "U kunt echter controleren of er iets op {0} staat.",
    InitializationDescription: "Houd je vast. We zijn nog steeds gegevens aan het laden.",
    InitializationTitle: "Initialiseren…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Tijdlijninformatie ontbreekt.",
    More: "Meer",
    NamesTitle: "namen",
    NoFamilyTreeInformation: "Geen stamboominformatie.",
    OpenInNewWindow: "Openen in een nieuw venster",
    PageNeedsEntityId: "Deze pagina heeft een entiteit ID als parameter nodig.",
    PositionsHeldTitle: "Banen die men heeft gehad",
    RelationsTitle: "Relaties",
    SiteLinksTitle: "Sitelinks",
    StarTheRepo: "Voeg ster toe aan de repository",
    SwitchLanguage: "Schakel taal",
    TimelineUntilNow: "Nu",
    UnknownValue: "Onbekend",
    WelcomeDescription: "Dit is een nog steeds lopende automatische stamboom voor de <i>Warriors</i>-serie. Typ iets in het onderstaande zoekvak om door te gaan. <br /> Bijv. typ <b>Firestar </b> en druk op enter.",
    WelcomeTitle: "Welkom",
};

export default prompts;
