import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Om denne appen",
    AboutThisAppDescription: "Eller gi tilbakemelding til oss",
    AffiliationsTitle: "bevisn",
    Brackets: "({0})",
    CharacterApprentice: "Lærling",
    CharacterApprentices: "lærlinger",
    CharacterChild: "Barn",
    CharacterChildren: "barn",
    CharacterMate: "Kompis",
    CharacterMates: "mates",
    CharacterMentor: "mentor",
    CharacterMentors: "mentorer",
    CharacterParent: "Parent",
    CharacterParents: "Foreldre",
    ContributeToTheDataSource: "Bidra til datakilden",
    DurationMoon: "måne",
    DurationMoons: "måner",
    DurationYear: "år",
    DurationYears: "år",
    EmbedAppMenu: "Klikk for å se flere handlinger",
    EmbedPoweredBy1: "Drevet av {0}",
    EntityNotFound1: "Ingen informasjon tilgjengelig for enheten: {0}.",
    EntityProfileTitle: "Enhetsprofil",
    EntitySearchBoxPlaceholder: "Søk etter en katt…",
    FamilyTreeTitle: "Familietre",
    FamilyTreeTitle1: "Slektstre til {0}",
    GoToEntityDataSource: "Gå til datakilden til denne enheten.",
    HoweverCheckout1: "Du kan imidlertid sjekke om det er noe på {0}.",
    InitializationDescription: "Hold fast. Vi laster fremdeles noen data.",
    InitializationTitle: "Initialiserer…",
    ListSeparator: ",",
    MissingTimelineInformation: "Manglende tidslinjeinformasjon.",
    More: "Mer",
    NamesTitle: "navnene",
    NoFamilyTreeInformation: "Ingen informasjon om slektstre.",
    OpenInNewWindow: "Åpne i nytt vindu",
    PageNeedsEntityId: "Denne siden trenger en enhets-ID som parameter.",
    PositionsHeldTitle: "Stillinger avholdt",
    RelationsTitle: "relasjoner",
    SiteLinksTitle: "Nettstedslenker",
    StarTheRepo: "Legg stjerne til depotet",
    SwitchLanguage: "Bytt språk",
    TimelineUntilNow: "Nå",
    UnknownValue: "Ukjent",
    WelcomeDescription: "Dette er et automatisk arbeid som er i gang med å jobbe i gang for <i>Warriors</i>-serien. Skriv inn noe i søkefeltet nedenfor for å fortsette. <br /> F.eks. skriv <b>Firestar</b> og trykk enter.",
    WelcomeTitle: "Velkommen"
};

export default prompts;
