import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "O tej aplikacji",
    AboutThisAppDescription: "Lub przekaż nam swoją opinię",
    AffiliationsTitle: "Przynależność",
    Brackets: "({0})",
    CharacterApprentice: "Uczeń",
    CharacterApprentices: "Praktykanci",
    CharacterChild: "Dziecko",
    CharacterChildren: "Dzieci",
    CharacterMate: "Kumpel",
    CharacterMates: "Przyjaciele",
    CharacterMentor: "Mentor",
    CharacterMentors: "Mentorzy",
    CharacterParent: "Rodzic",
    CharacterParents: "Rodzice",
    ContributeToTheDataSource: "Przyczynić się do źródła danych",
    DurationMoon: "księżyc",
    DurationMoons: "księżyce",
    DurationYear: "rok",
    DurationYears: "lat",
    EmbedAppMenu: "Kliknij, aby zobaczyć więcej działań",
    EmbedPoweredBy1: "Obsługiwane przez {0}",
    EntityNotFound1: "Brak dalszych informacji dla jednostki: {0}.",
    EntityProfileTitle: "Profil podmiotu",
    EntitySearchBoxPlaceholder: "Wyszukaj kota…",
    FamilyTreeTitle: "Drzewo rodzinne",
    FamilyTreeTitle1: "Drzewo genealogiczne {0}",
    GoToEntityDataSource: "Przejdź do źródła danych tego podmiotu.",
    HoweverCheckout1: "Możesz jednak sprawdzić, czy coś jest na {0}.",
    InitializationDescription: "Trzymaj się. Wciąż ładujemy niektóre dane.",
    InitializationTitle: "Inicjowanie…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Brakuje informacji o osi czasu.",
    More: "Więcej",
    NamesTitle: "Nazwy",
    NoFamilyTreeInformation: "Brak informacji o drzewie genealogicznym.",
    OpenInNewWindow: "Otworzyć w nowym oknie",
    PageNeedsEntityId: "Ta strona wymaga ID jednostki jako parametru.",
    PositionsHeldTitle: "Zajmowane stanowiska",
    RelationsTitle: "Relacje",
    SiteLinksTitle: "Linki do stron",
    StarTheRepo: "Dodaj gwiazdkę do repozytorium",
    SwitchLanguage: "Zmień język",
    TimelineUntilNow: "Teraz",
    UnknownValue: "Nieznany",
    WelcomeDescription: "Jest to wciąż automatyczne drzewo genealogiczne pracujące w toku dla serii <i>Warriors</i>. Wpisz coś w polu wyszukiwania poniżej, aby kontynuować. <br /> Np. wpisz <b>Firestar </b> i naciśnij enter.",
    WelcomeTitle: "Witamy",
};

export default prompts;
