import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Об этом приложении",
    AboutThisAppDescription: "Или оставьте отзыв",
    AffiliationsTitle: "принадлежность",
    Brackets: "({0})",
    CharacterApprentice: "подмастерье",
    CharacterApprentices: "Ученики",
    CharacterChild: "ребенок",
    CharacterChildren: "Дети",
    CharacterMate: "Приятель",
    CharacterMates: "Помощники",
    CharacterMentor: "Наставник",
    CharacterMentors: "Наставники",
    CharacterParent: "родитель",
    CharacterParents: "Родители",
    ContributeToTheDataSource: "Вклад в источник данных",
    DurationMoon: "Луна",
    DurationMoons: "спутники",
    DurationYear: "год",
    DurationYears: "лет",
    EmbedAppMenu: "Нажмите, чтобы увидеть больше действий",
    EmbedPoweredBy1: "Работает на {0}",
    EntityNotFound1: "Для объекта больше нет информации: {0}.",
    EntityProfileTitle: "Профиль объекта",
    EntitySearchBoxPlaceholder: "Ищите кота…",
    FamilyTreeTitle: "Семейное дерево",
    FamilyTreeTitle1: "Семейное древо {0}",
    GoToEntityDataSource: "Перейти к источнику данных этой сущности.",
    HoweverCheckout1: "Однако вы можете проверить, есть ли что-то в {0}.",
    InitializationDescription: "Держись крепче Мы все еще загружаем некоторые данные.",
    InitializationTitle: "Инициализация…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Отсутствует информация о сроках.",
    More: "Больше",
    NamesTitle: "имена",
    NoFamilyTreeInformation: "Нет информации о генеалогическом древе.",
    OpenInNewWindow: "Открыть в новом окне",
    PageNeedsEntityId: "Эта страница нуждается в идентификаторе объекта в качестве параметра.",
    PositionsHeldTitle: "Занимаемые должности",
    RelationsTitle: "связи",
    SiteLinksTitle: "Ссылки сайта",
    StarTheRepo: "Добавить звезду в хранилище",
    SwitchLanguage: "Смена языка",
    TimelineUntilNow: "В настоящее время",
    UnknownValue: "неизвестный",
    WelcomeDescription: "Это все еще незавершенное автоматическое семейное древо для серии «Коты-воители». Чтобы продолжить, введите что-нибудь в поле поиска. <br />Например. введите <b>Огнезвёзд</b> и нажмите ввод.",
    WelcomeTitle: "желанный",
};

export default prompts;
