SELECT DISTINCT ?entity ?desc
WHERE {
  VALUES ?typeEntity {
    wd:Q624     # fictional character
    wd:Q109     # chapter
    wd:Q46      # book
    wd:Q633     # fictional group of cats
  }
  ?entity   wdt:P3/wdt:P4*      ?typeEntity.
  ?entity   schema:description  ?desc.
}
