import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "O této aplikaci",
    AboutThisAppDescription: "Nebo nám poskytněte zpětnou vazbu",
    AffiliationsTitle: "Přidružení",
    Brackets: "({0})",
    CharacterApprentice: "Učeň",
    CharacterApprentices: "Učni",
    CharacterChild: "Dítě",
    CharacterChildren: "Děti",
    CharacterMate: "Mate",
    CharacterMates: "Mates",
    CharacterMentor: "Mentore",
    CharacterMentors: "Mentoři",
    CharacterParent: "Rodič",
    CharacterParents: "Rodiče",
    ContributeToTheDataSource: "Přispějte ke zdroji dat",
    DurationMoon: "měsíc",
    DurationMoons: "měsíce",
    DurationYear: "rok",
    DurationYears: "let",
    EmbedAppMenu: "Klepnutím zobrazíte další akce",
    EmbedPoweredBy1: "Běží na {0}",
    EntityNotFound1: "Žádné další informace o subjektu nejsou k dispozici: {0}.",
    EntityProfileTitle: "Profil entity",
    EntitySearchBoxPlaceholder: "Hledejte kočku ...",
    FamilyTreeTitle: "Rodokmen",
    FamilyTreeTitle1: "Rodokmen {0}",
    GoToEntityDataSource: "Přejít na zdroj dat této entity.",
    HoweverCheckout1: "Můžete si však zkontrolovat, zda je něco na {0}.",
    InitializationDescription: "Počkejte, stále načítáme některá data.",
    InitializationTitle: "Inicializace ...",
    ListSeparator: ",",
    MissingTimelineInformation: "Chybějící informace o časové ose.",
    More: "Více",
    NamesTitle: "Jména",
    NoFamilyTreeInformation: "Žádné informace o rodokmenu.",
    OpenInNewWindow: "Otevřít v novém okně",
    PageNeedsEntityId: "Tato stránka potřebuje jako parametr ID entity.",
    PositionsHeldTitle: "Pozice drženy",
    RelationsTitle: "Vztahy",
    SiteLinksTitle: "Odkazy na stránky",
    StarTheRepo: "Přidejte do úložiště hvězdu",
    SwitchLanguage: "Přepnout jazyk",
    TimelineUntilNow: "Teď",
    UnknownValue: "Neznámý",
    WelcomeDescription: "Toto je stále nedokončený automatický rodokmen pro řadu <i> Warriors </ i>. Chcete-li pokračovat, zadejte něco do vyhledávacího pole níže. <br /> Např. <b> Firestar </ b> a stiskněte klávesu enter .",
    WelcomeTitle: "Vítejte",
};

export default prompts;
