import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Om denne app",
    AboutThisAppDescription: "Eller give feedback til os",
    AffiliationsTitle: "Samarbejdspartnere",
    Brackets: "({0})",
    CharacterApprentice: "Lærling",
    CharacterApprentices: "Lærlinge",
    CharacterChild: "Barn",
    CharacterChildren: "børn",
    CharacterMate: "Parrer sig",
    CharacterMates: "Mates",
    CharacterMentor: "Mentor",
    CharacterMentors: "mentorer",
    CharacterParent: "Forældre",
    CharacterParents: "Forældre",
    ContributeToTheDataSource: "Bidrag til datakilden",
    DurationMoon: "måne",
    DurationMoons: "måner",
    DurationYear: "år",
    DurationYears: "flere år",
    EmbedAppMenu: "Klik for at se flere handlinger",
    EmbedPoweredBy1: "Drives af {0}",
    EntityNotFound1: "Der er ikke flere tilgængelige oplysninger for virksomheden: {0}.",
    EntityProfileTitle: "Enhedsprofil",
    EntitySearchBoxPlaceholder: "Søg efter en kat…",
    FamilyTreeTitle: "Familie træ",
    FamilyTreeTitle1: "Slægtstræ fra {0}",
    GoToEntityDataSource: "Gå til datakilden for denne enhed.",
    HoweverCheckout1: "Du kan dog kontrollere, om der er noget på {0}.",
    InitializationDescription: "Hold fast. Vi indlæser stadig nogle data.",
    InitializationTitle: "Initialiserer…",
    ListSeparator: ",",
    MissingTimelineInformation: "Manglende tidslinjeoplysninger.",
    More: "Mere",
    NamesTitle: "navne",
    NoFamilyTreeInformation: "Ingen oplysninger om slægtstræer.",
    OpenInNewWindow: "Åbn i nyt vindue",
    PageNeedsEntityId: "Denne side har brug for et enheds-id som parameter.",
    PositionsHeldTitle: "Stillinger afholdt",
    RelationsTitle: "forbindelser",
    SiteLinksTitle: "Webstedslink",
    StarTheRepo: "Føj stjerne til depotet",
    SwitchLanguage: "Skift sprog",
    TimelineUntilNow: "Nu",
    UnknownValue: "Ukendt",
    WelcomeDescription: "Dette er et stadig arbejde-i-igangværende automatisk slægtstræ til <i>Warriors</i>-serien. Skriv noget i søgefeltet nedenfor for at fortsætte. <br /> F.eks. skriv <b>Firestar</b> og tryk på enter.",
    WelcomeTitle: "Velkommen"
};

export default prompts;
