import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "partial-machine-translation",
    AboutThisApp: "Über diese App",
    AboutThisAppDescription: "Oder geben Sie uns Feedback",
    AffiliationsTitle: "Mitgliedschaften",
    Brackets: "({0})",
    CharacterApprentice: "Schüler(in)",
    CharacterApprentices: "Schüler(in)",
    CharacterChild: "Kind",
    CharacterChildren: "Kinder",
    CharacterMate: "Gefährte/Gefährtin",
    CharacterMates: "Gefährten/Gefährtinnen",
    CharacterMentor: "Mentor",
    CharacterMentors: "Mentoren",
    CharacterParent: "Elternteil",
    CharacterParents: "Eltern",
    ContributeToTheDataSource: "Tragen Sie zur Datenquelle bei",
    DurationMoon: "Mond",
    DurationMoons: "Monde",
    DurationYear: "Jahr",
    DurationYears: "Jahre",
    EmbedAppMenu: "Klicken Sie hier, um weitere Aktionen anzuzeigen",
    EmbedPoweredBy1: "Bereitgestellt von {0}",
    EntityNotFound1: "Für die Entität sind keine weiteren Informationen verfügbar: {0}.",
    EntityProfileTitle: "Entitätsprofil",
    EntitySearchBoxPlaceholder: "Suche nach einer Katze…",
    FamilyTreeTitle: "Stammbaum",
    FamilyTreeTitle1: "Stammbaum von {0}",
    GoToEntityDataSource: "Gehe zur Datenquelle dieser Entität.",
    HoweverCheckout1: "Sie können jedoch überprüfen, ob sich auf {0} etwas befindet.",
    InitializationDescription: "Halten Sie sich fest. Wir laden noch einige Daten.",
    InitializationTitle: "Initialisierung…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Fehlende Timeline-Informationen.",
    More: "Mehr",
    NamesTitle: "Namen",
    NoFamilyTreeInformation: "Keine Informationen zum Stammbaum.",
    OpenInNewWindow: "In neuem Fenster öffnen",
    PageNeedsEntityId: "Diese Seite benötigt eine Entity-ID als Parameter.",
    PositionsHeldTitle: "Positionen gehalten",
    RelationsTitle: "Beziehungen",
    SiteLinksTitle: "Site-Links",
    StarTheRepo: "Fügen Sie dem Repository einen Stern hinzu",
    SwitchLanguage: "Sprache wechseln",
    TimelineUntilNow: "Jetzt",
    UnknownValue: "Unbekannt",
    WelcomeDescription: "Dies ist ein noch laufender automatischer Stammbaum für die <i>Warrior Cats</i> serie. Geben Sie etwas in das Suchfeld unten ein, um fortzufahren. <br /> Geben Sie beispielsweise <b>Feuerstern</b> ein und drücken Sie die Eingabetaste .",
    WelcomeTitle: "Herzlich willkommen",
};

export default prompts;
