import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Acerca de esta aplicación",
    AboutThisAppDescription: "O envíenos sus comentarios",
    AffiliationsTitle: "Afiliaciones",
    Brackets: "({0})",
    CharacterApprentice: "Aprendiz",
    CharacterApprentices: "Aprendices",
    CharacterChild: "Niño",
    CharacterChildren: "Niños",
    CharacterMate: "Compañero",
    CharacterMates: "Compañeros",
    CharacterMentor: "Mentor",
    CharacterMentors: "Mentores",
    CharacterParent: "Padre",
    CharacterParents: "Padres",
    ContributeToTheDataSource: "Contribuir a la fuente de datos",
    DurationMoon: "Luna",
    DurationMoons: "lunas",
    DurationYear: "año",
    DurationYears: "años",
    EmbedAppMenu: "Haga clic para ver más acciones.",
    EmbedPoweredBy1: "Desarrollado por {0}",
    EntityNotFound1: "No hay más información disponible para la entidad: {0}.",
    EntityProfileTitle: "Perfil de entidad",
    EntitySearchBoxPlaceholder: "Busca un gato…",
    FamilyTreeTitle: "Árbol de familia",
    FamilyTreeTitle1: "Árbol genealógico de {0}",
    GoToEntityDataSource: "Ir a la fuente de datos de esta entidad.",
    HoweverCheckout1: "Sin embargo, puede verificar si hay algo en {0}.",
    InitializationDescription: "Agárrate fuerte. Todavía estamos cargando algunos datos.",
    InitializationTitle: "Inicializando…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Falta información de la línea de tiempo.",
    More: "Más",
    NamesTitle: "Nombres",
    NoFamilyTreeInformation: "No hay información del árbol genealógico.",
    OpenInNewWindow: "Abrir en Nueva ventana",
    PageNeedsEntityId: "Esta página necesita una ID de entidad como parámetro.",
    PositionsHeldTitle: "Cargos desempeñados",
    RelationsTitle: "Relaciones",
    SiteLinksTitle: "Enlaces del sitio",
    StarTheRepo: "Agregar estrella al repositorio",
    SwitchLanguage: "Cambiar de idioma",
    TimelineUntilNow: "Ahora",
    UnknownValue: "Desconocido",
    WelcomeDescription: "Este es un árbol genealógico automático todavía en progreso para la serie <i>Warriors</i>. Escriba algo en el cuadro de búsqueda a continuación para continuar. <br /> Por ejemplo. escriba <b>Firestar </b> y presione Entrar.",
    WelcomeTitle: "Bienvenido",
};

export default prompts;
