import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Tietoja tästä sovelluksesta",
    AboutThisAppDescription: "Tai anna palautetta meille",
    AffiliationsTitle: "kytkökset",
    Brackets: "({0})",
    CharacterApprentice: "Oppipoika",
    CharacterApprentices: "oppisopimuskoulutuksessa",
    CharacterChild: "Lapsi",
    CharacterChildren: "lapset",
    CharacterMate: "perämies",
    CharacterMates: "Kaverit",
    CharacterMentor: "opastaja",
    CharacterMentors: "mentorit",
    CharacterParent: "vanhempi",
    CharacterParents: "Vanhemmat",
    ContributeToTheDataSource: "Osallistu tietolähteeseen",
    DurationMoon: "kuu",
    DurationMoons: "kuut",
    DurationYear: "vuosi",
    DurationYears: "vuotta",
    EmbedAppMenu: "Napsauta nähdäksesi lisää toimintoja",
    EmbedPoweredBy1: "Powered by {0}",
    EntityNotFound1: "Yksiköstä ei ole saatavilla lisätietoja: {0}.",
    EntityProfileTitle: "Yhteisöprofiili",
    EntitySearchBoxPlaceholder: "Etsi kissa…",
    FamilyTreeTitle: "Sukupuu",
    FamilyTreeTitle1: "Sukupuu {0}",
    GoToEntityDataSource: "Siirry tämän yksikön tietolähteeseen.",
    HoweverCheckout1: "Voit kuitenkin tarkistaa, onko {0} -palvelussa jotain.",
    InitializationDescription: "Pidä tiukasti. Olemme edelleen lataamassa joitain tietoja.",
    InitializationTitle: "Alustetaan…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Puuttuvat aikajanatiedot.",
    More: "Lisää",
    NamesTitle: "nimet",
    NoFamilyTreeInformation: "Ei sukupuuta koskevia tietoja.",
    OpenInNewWindow: "Avaa uudessa ikkunassa",
    PageNeedsEntityId: "Tämä sivu tarvitsee yksikön tunnuksen parametrina.",
    PositionsHeldTitle: "Asemat pidetty",
    RelationsTitle: "Suhteet",
    SiteLinksTitle: "Sivustolinkit",
    StarTheRepo: "Lisää tähti arkistoon",
    SwitchLanguage: "Vaihda kieli",
    TimelineUntilNow: "Nyt",
    UnknownValue: "Tuntematon",
    WelcomeDescription: "Tämä on edelleen keskeneräinen automaattinen sukupuu <i>Warriors</i> -sarjalle. Kirjoita jotain alla olevaan hakukenttään jatkaaksesi. <br /> Esimerkki: kirjoita <b>Firestar </b> ja paina enter.",
    WelcomeTitle: "Tervetuloa",
};

export default prompts;
