import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "complete",
    AboutThisApp: "À propos de cette application",
    AboutThisAppDescription: "Ou nous faire part de vos commentaires",
    AffiliationsTitle: "Affiliations",
    Brackets: "({0})",
    CharacterApprentice: "Apprenti",
    CharacterApprentices: "Apprentis",
    CharacterChild: "Enfant",
    CharacterChildren: "Enfants",
    CharacterMate: "Partenaire",
    CharacterMates: "Partenaires",
    CharacterMentor: "Mentor",
    CharacterMentors: "Mentors",
    CharacterParent: "Parent",
    CharacterParents: "Parents",
    ContributeToTheDataSource: "Contribuer à la base de données",
    DurationMoon: "lune",
    DurationMoons: "lunes",
    DurationYear: "an",
    DurationYears: "ans",
    EmbedAppMenu: "Cliquez pour voir plus d'actions",
    EmbedPoweredBy1: "Fonctionne avec {0}",
    EntityNotFound1: "Aucune information disponible pour {0}.",
    EntityProfileTitle: "Profil",
    EntitySearchBoxPlaceholder: "Rechercher un chat…",
    FamilyTreeTitle: "Arbre généalogique",
    FamilyTreeTitle1: "Arbre généalogique de {0}",
    GoToEntityDataSource: "Aller à la base de données.",
    HoweverCheckout1: "Cependant, vous pouvez vérifier s'il y a quelque chose sur {0}.",
    InitializationDescription: "Données en cours de chargement.",
    InitializationTitle: "Initialisation…",
    ListSeparator: ", ",
    MissingTimelineInformation: "Chronologie manquante.",
    More: "Plus",
    NamesTitle: "Noms",
    NoFamilyTreeInformation: "Aucune information sur l'arbre généalogique.",
    OpenInNewWindow: "Ouvrir dans une nouvelle fenetre",
    PageNeedsEntityId: "Cette page nécessite un identifiant d'entité en paramètre.",
    PositionsHeldTitle: "Rangs",
    RelationsTitle: "Relations",
    SiteLinksTitle: "Liens du site",
    StarTheRepo: "Ajouter une étoile au référentiel",
    SwitchLanguage: "Changer de langue",
    TimelineUntilNow: "Actuellement",
    UnknownValue: "Inconnu",
    WelcomeDescription: "Cette application est un arbre généalogique automatique en cours de création pour <i>La Guerre des Clans/i>. Tapez quelque chose dans la case de recherche ci-dessous pour continuer. <br /> Ex. tapez <b>Étoile de Feu</b> et appuyez sur Entrée.",
    WelcomeTitle: "Bienvenue",
};

export default prompts;
