import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "À propos de cette application",
    AboutThisAppDescription: "Ou nous faire part de vos commentaires",
    AffiliationsTitle: "Les affiliations",
    Brackets: "({0})",
    CharacterApprentice: "Apprenti",
    CharacterApprentices: "Les apprentis",
    CharacterChild: "Enfant",
    CharacterChildren: "Les enfants",
    CharacterMate: "Camarade",
    CharacterMates: "Camarades",
    CharacterMentor: "Mentor",
    CharacterMentors: "Mentors",
    CharacterParent: "Parent",
    CharacterParents: "Parents",
    ContributeToTheDataSource: "Contribuer à la source de données",
    DurationMoon: "lune",
    DurationMoons: "des lunes",
    DurationYear: "an",
    DurationYears: "ans",
    EmbedAppMenu: "Cliquez pour voir plus d'actions",
    EmbedPoweredBy1: "Propulsé par {0}",
    EntityNotFound1: "Aucune information supplémentaire disponible pour l'entité: {0}.",
    EntityProfileTitle: "Profil d'entité",
    EntitySearchBoxPlaceholder: "Rechercher un chat…",
    FamilyTreeTitle: "Arbre généalogique",
    FamilyTreeTitle1: "Arbre généalogique de {0}",
    GoToEntityDataSource: "Aller à la source de données de cette entité.",
    HoweverCheckout1: "Cependant, vous pouvez vérifier s'il y a quelque chose sur {0}.",
    InitializationDescription: "Tiens toi bien. Nous sommes toujours en train de charger des données.",
    InitializationTitle: "Initialisation…",
    ListSeparator: ",",
    MissingTimelineInformation: "Informations manquantes sur la chronologie.",
    More: "Plus",
    NamesTitle: "Noms",
    NoFamilyTreeInformation: "Aucune information sur l'arbre généalogique.",
    OpenInNewWindow: "Ouvrir dans une nouvelle fenetre",
    PageNeedsEntityId: "Cette page nécessite un identifiant d'entité en paramètre.",
    PositionsHeldTitle: "Postes occupés",
    RelationsTitle: "Rapports",
    SiteLinksTitle: "Liens du site",
    StarTheRepo: "Ajouter une étoile au référentiel",
    SwitchLanguage: "Changer de langue",
    TimelineUntilNow: "À présent",
    UnknownValue: "Inconnu",
    WelcomeDescription: "Il s'agit d'un arbre généalogique automatique en cours de création pour la série <i> Warriors </ i>. Tapez quelque chose dans la case de recherche ci-dessous pour continuer. <br /> E.g. tapez <b> Firestar </ b> et appuyez sur Entrée.",
    WelcomeTitle: "Bienvenue",
};

export default prompts;
