import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Erről az alkalmazásról",
    AboutThisAppDescription: "Vagy adjon visszajelzést nekünk",
    AffiliationsTitle: "hovatartozás",
    Brackets: "({0})",
    CharacterApprentice: "ipari tanuló",
    CharacterApprentices: "Apprentices",
    CharacterChild: "Gyermek",
    CharacterChildren: "Gyermekek",
    CharacterMate: "Társ",
    CharacterMates: "Mates",
    CharacterMentor: "tanácsadó",
    CharacterMentors: "mentorok",
    CharacterParent: "Szülő",
    CharacterParents: "A szülők",
    ContributeToTheDataSource: "Hozzájárulás az adatforráshoz",
    DurationMoon: "hold",
    DurationMoons: "holdak",
    DurationYear: "év",
    DurationYears: "évek",
    EmbedAppMenu: "Kattintson a további műveletek megtekintéséhez",
    EmbedPoweredBy1: "Támogatja a (z) {0}",
    EntityNotFound1: "Nincs több információ az entitásról: {0}.",
    EntityProfileTitle: "Entitási profil",
    EntitySearchBoxPlaceholder: "Keressen macskát…",
    FamilyTreeTitle: "Családfa",
    FamilyTreeTitle1: "A (z) {0} családfa",
    GoToEntityDataSource: "Nyissa meg az entitás adatforrását.",
    HoweverCheckout1: "Ellenőrizheti, hogy van-e valami a {0} oldalon.",
    InitializationDescription: "Kapaszkodj erősen. Még mindig töltünk be néhány adatot.",
    InitializationTitle: "Indítás…",
    ListSeparator: ",",
    MissingTimelineInformation: "Hiányzik az idővonal-információ.",
    More: "Több",
    NamesTitle: "nevek",
    NoFamilyTreeInformation: "Nincs családfa információ.",
    OpenInNewWindow: "Megnyitás új ablakban",
    PageNeedsEntityId: "Ezen az oldalon paraméterként entitás azonosítóra van szükség.",
    PositionsHeldTitle: "Pozíciók megtartása",
    RelationsTitle: "Relations",
    SiteLinksTitle: "Webhely linkei",
    StarTheRepo: "Csillag hozzáadása a lerakathoz",
    SwitchLanguage: "Váltás a nyelvre",
    TimelineUntilNow: "Most",
    UnknownValue: "Ismeretlen",
    WelcomeDescription: "Ez egy még folyamatban lévő folyamatban lévő automatikus családfa a <i>Warriors</i> sorozat számára. A folytatáshoz írjon be valamit az alábbi keresőmezőbe. <br /> Például. írja be a <b>Firestar</b> menüpontot, és nyomja meg az enter billentyűt.",
    WelcomeTitle: "Üdvözöljük"
};

export default prompts;
