import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "A proposito di questa app",
    AboutThisAppDescription: "O forniscici un feedback",
    AffiliationsTitle: "affiliazioni",
    Brackets: "({0})",
    CharacterApprentice: "Apprendista",
    CharacterApprentices: "apprendisti",
    CharacterChild: "Bambino",
    CharacterChildren: "Bambini",
    CharacterMate: "Compagno",
    CharacterMates: "mates",
    CharacterMentor: "Mentore",
    CharacterMentors: "mentori",
    CharacterParent: "Genitore",
    CharacterParents: "genitori",
    ContributeToTheDataSource: "Contribuire alla fonte di dati",
    DurationMoon: "Luna",
    DurationMoons: "lune",
    DurationYear: "anno",
    DurationYears: "anni",
    EmbedAppMenu: "Fai clic per vedere più azioni",
    EmbedPoweredBy1: "Offerto da {0}",
    EntityNotFound1: "Non ci sono ulteriori informazioni disponibili per l'entità: {0}.",
    EntityProfileTitle: "Profilo dell'entità",
    EntitySearchBoxPlaceholder: "Cerca un gatto ...",
    FamilyTreeTitle: "Albero genealogico",
    FamilyTreeTitle1: "Albero genealogico di {0}",
    GoToEntityDataSource: "Vai all'origine dati di questa entità.",
    HoweverCheckout1: "Tuttavia, puoi verificare se c'è qualcosa su {0}.",
    InitializationDescription: "Tieni duro. Stiamo ancora caricando alcuni dati.",
    InitializationTitle: "Inizializzazione ...",
    ListSeparator: ",",
    MissingTimelineInformation: "Informazioni sulla cronologia mancanti.",
    More: "Di Più",
    NamesTitle: "nomi",
    NoFamilyTreeInformation: "Nessuna informazione sull'albero genealogico.",
    OpenInNewWindow: "Apri in una nuova finestra",
    PageNeedsEntityId: "Questa pagina richiede un ID entità come parametro.",
    PositionsHeldTitle: "Posizioni detenute",
    RelationsTitle: "Relazioni",
    SiteLinksTitle: "Link al sito",
    StarTheRepo: "Aggiungi stella al repository",
    SwitchLanguage: "Cambia lingua",
    TimelineUntilNow: "Adesso",
    UnknownValue: "Sconosciuto",
    WelcomeDescription: "Questo è un albero genealogico automatico ancora in corso per la serie <i> Warriors </i>. Digita qualcosa nella casella di ricerca in basso per continuare. <br /> Ad esempio digitare <b> Firestar </b> e premere invio.",
    WelcomeTitle: "benvenuto",
};

export default prompts;
