import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "このアプリについて",
    AboutThisAppDescription: "またはフィードバックをお寄せください",
    AffiliationsTitle: "所属",
    Brackets: "（{0}）",
    CharacterApprentice: "見習い",
    CharacterApprentices: "見習い",
    CharacterChild: "子",
    CharacterChildren: "子供",
    CharacterMate: "メイト",
    CharacterMates: "合致",
    CharacterMentor: "メンター",
    CharacterMentors: "メンター",
    CharacterParent: "親",
    CharacterParents: "親",
    ContributeToTheDataSource: "データソースへの貢献",
    DurationMoon: "月",
    DurationMoons: "月",
    DurationYear: "年",
    DurationYears: "年",
    EmbedAppMenu: "クリックして他のアクションを表示",
    EmbedPoweredBy1: "{0}を搭載",
    EntityNotFound1: "エンティティに関する情報はこれ以上ありません：{0}。",
    EntityProfileTitle: "エンティティプロファイル",
    EntitySearchBoxPlaceholder: "猫を検索…",
    FamilyTreeTitle: "家系図",
    FamilyTreeTitle1: "{0}の家系図",
    GoToEntityDataSource: "このエンティティのデータソースに移動します。",
    HoweverCheckout1: "ただし、{0}に何かがあるかどうかを確認できます。",
    InitializationDescription: "しっかりホールド。 まだデータを読み込んでいます。",
    InitializationTitle: "初期化しています…",
    ListSeparator: "、",
    MissingTimelineInformation: "タイムライン情報がありません。",
    More: "もっと",
    NamesTitle: "お名前",
    NoFamilyTreeInformation: "家系図情報はありません。",
    OpenInNewWindow: "新しいウィンドウで開きます",
    PageNeedsEntityId: "このページには、パラメータとしてエンティティIDが必要です。",
    PositionsHeldTitle: "肩書き",
    RelationsTitle: "関係",
    SiteLinksTitle: "サイトリンク",
    StarTheRepo: "リポジトリにスターを追加",
    SwitchLanguage: "言語を切り替える",
    TimelineUntilNow: "いま",
    UnknownValue: "未知の",
    WelcomeDescription: "これは、<i> Warriors </ i>シリーズのまだ進行中の自動ファミリーツリーです。 続行するには、下の検索ボックスに何かを入力してください。<br />例 「<b> Firestar </ b>」と入力してEnterキーを押します。",
    WelcomeTitle: "ようこそ",
};

export default prompts;
