import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "이 앱에 대하여",
    AboutThisAppDescription: "또는 우리에게 피드백을 제공",
    AffiliationsTitle: "소속",
    Brackets: "({0})",
    CharacterApprentice: "도제",
    CharacterApprentices: "견습생",
    CharacterChild: "어린이",
    CharacterChildren: "어린이",
    CharacterMate: "항해사",
    CharacterMates: "메이트",
    CharacterMentor: "멘토르",
    CharacterMentors: "멘토",
    CharacterParent: "부모의",
    CharacterParents: "부모님",
    ContributeToTheDataSource: "데이터 소스에 기여",
    DurationMoon: "달",
    DurationMoons: "달",
    DurationYear: "년",
    DurationYears: "연령",
    EmbedAppMenu: "추가 조치를 보려면 클릭하십시오",
    EmbedPoweredBy1: "{0}에 의해 구동",
    EntityNotFound1: "엔티티에 대한 추가 정보가 없습니다 : {0}.",
    EntityProfileTitle: "엔터티 프로필",
    EntitySearchBoxPlaceholder: "고양이 찾기…",
    FamilyTreeTitle: "가계도",
    FamilyTreeTitle1: "{0}의 가계도",
    GoToEntityDataSource: "이 엔티티의 데이터 소스로 이동하십시오.",
    HoweverCheckout1: "그러나 {0}에 무언가가 있는지 확인할 수 있습니다.",
    InitializationDescription: "꽉 잡아. 아직 일부 데이터를로드 중입니다.",
    InitializationTitle: "초기화 중…",
    ListSeparator: ",",
    MissingTimelineInformation: "타임 라인 정보가 누락되었습니다.",
    More: "더",
    NamesTitle: "이름",
    NoFamilyTreeInformation: "가계도 정보가 없습니다.",
    OpenInNewWindow: "새창에서 열기",
    PageNeedsEntityId: "이 페이지에는 매개 변수로 엔티티 ID가 필요합니다.",
    PositionsHeldTitle: "개최 포지션",
    RelationsTitle: "처지",
    SiteLinksTitle: "사이트 링크",
    StarTheRepo: "저장소에 별표 추가",
    SwitchLanguage: "언어 전환",
    TimelineUntilNow: "지금",
    UnknownValue: "알 수 없는",
    WelcomeDescription: "이것은 여전히 <i> 워리어 </ i> 시리즈의 진행중인 자동 패밀리 트리입니다. 계속하려면 아래 검색 창에 무언가를 입력하십시오. <br /> 예 : <b> Firestar </ b>를 입력하고 Enter를 누르십시오.",
    WelcomeTitle: "환영",
};

export default prompts;
