import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Sobre este aplicativo",
    AboutThisAppDescription: "Ou envie-nos um feedback",
    AffiliationsTitle: "Afiliações",
    Brackets: "({0})",
    CharacterApprentice: "Aprendiz",
    CharacterApprentices: "Aprendizes",
    CharacterChild: "Criança",
    CharacterChildren: "Crianças",
    CharacterMate: "Companheiro",
    CharacterMates: "Companheiros",
    CharacterMentor: "Mentor",
    CharacterMentors: "Mentores",
    CharacterParent: "Pai",
    CharacterParents: "Pais",
    ContributeToTheDataSource: "Contribua para a fonte de dados",
    DurationMoon: "lua",
    DurationMoons: "luas",
    DurationYear: "ano",
    DurationYears: "anos",
    EmbedAppMenu: "Clique para ver mais ações",
    EmbedPoweredBy1: "Desenvolvido por {0}",
    EntityNotFound1: "Não há mais informações disponíveis para a entidade: {0}.",
    EntityProfileTitle: "Perfil da entidade",
    EntitySearchBoxPlaceholder: "Procure um gato…",
    FamilyTreeTitle: "Árvore genealógica",
    FamilyTreeTitle1: "Árvore genealógica de {0}",
    GoToEntityDataSource: "Vá para a fonte de dados desta entidade.",
    HoweverCheckout1: "No entanto, você pode verificar se há algo em {0}.",
    InitializationDescription: "Apertar. Ainda estamos carregando alguns dados.",
    InitializationTitle: "Inicializando…",
    ListSeparator: ",",
    MissingTimelineInformation: "Faltam informações da linha do tempo.",
    More: "Mais",
    NamesTitle: "Nomes",
    NoFamilyTreeInformation: "Nenhuma informação de árvore genealógica.",
    OpenInNewWindow: "Abrir em uma nova janela",
    PageNeedsEntityId: "Esta página precisa de um ID da entidade como parâmetro.",
    PositionsHeldTitle: "Cargos ocupados",
    RelationsTitle: "Relações",
    SiteLinksTitle: "Links do site",
    StarTheRepo: "Adicionar estrela ao repositório",
    SwitchLanguage: "Mudar idioma",
    TimelineUntilNow: "Agora",
    UnknownValue: "Desconhecido",
    WelcomeDescription: "Esta é uma árvore genealógica automática ainda em andamento para a série <i>Warriors</i>. Digite algo na caixa de pesquisa abaixo para continuar. <br /> Por exemplo, digite <b>Firestar</b> e pressione enter.",
    WelcomeTitle: "Bem vinda"
};

export default prompts;
