import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "machine-translation",
    AboutThisApp: "Про цю програму",
    AboutThisAppDescription: "Або надішліть нам відгуки",
    AffiliationsTitle: "Філії",
    Brackets: "({0})",
    CharacterApprentice: "Учень",
    CharacterApprentices: "Учні",
    CharacterChild: "Дитина",
    CharacterChildren: "Діти",
    CharacterMate: "Мате",
    CharacterMates: "Товариші",
    CharacterMentor: "Вихователь",
    CharacterMentors: "Наставники",
    CharacterParent: "Батьківський",
    CharacterParents: "Батьки",
    ContributeToTheDataSource: "Зробіть внесок у джерело даних",
    DurationMoon: "місяць",
    DurationMoons: "місяці",
    DurationYear: "рік",
    DurationYears: "років",
    EmbedAppMenu: "Клацніть, щоб переглянути інші дії",
    EmbedPoweredBy1: "Працює на {0}",
    EntityNotFound1: "Більше інформації для юридичної особи немає: {0}.",
    EntityProfileTitle: "Профіль юридичної особи",
    EntitySearchBoxPlaceholder: "Пошук кота…",
    FamilyTreeTitle: "Родинне дерево",
    FamilyTreeTitle1: "Родинне дерево {0}",
    GoToEntityDataSource: "Перейдіть до джерела даних цього об'єкта.",
    HoweverCheckout1: "Однак ви можете перевірити, чи є щось на {0}.",
    InitializationDescription: "Тримайся міцно. Ми все ще завантажуємо деякі дані.",
    InitializationTitle: "Ініціалізація ...",
    ListSeparator: ",",
    MissingTimelineInformation: "Інформація про часову шкалу відсутня",
    More: "Більше",
    NamesTitle: "Імена",
    NoFamilyTreeInformation: "Немає даних про родинне дерево.",
    OpenInNewWindow: "Відкрити у новому вікні",
    PageNeedsEntityId: "На цій сторінці в якості параметра потрібен ідентифікатор особи.",
    PositionsHeldTitle: "Посади займали",
    RelationsTitle: "Відносини",
    SiteLinksTitle: "Посилання на сайт",
    StarTheRepo: "Додайте зірочку до сховища",
    SwitchLanguage: "Мова переключення",
    TimelineUntilNow: "Тепер",
    UnknownValue: "Невідомо",
    WelcomeDescription: "Це все ще незавершене автоматичне сімейне дерево для серії <i> Warriors </i>. Введіть щось у поле пошуку нижче, щоб продовжити. <br /> Наприклад наберіть <b> Firestar </b> і натисніть клавішу Enter.",
    WelcomeTitle: "Ласкаво просимо",
};

export default prompts;
