import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    __STATUS: "complete",
    AboutThisApp: "关于此应用",
    AboutThisAppDescription: "或者向我们提供反馈意见",
    AffiliationsTitle: "隶属关系",
    Brackets: "（{0}）",
    CharacterApprentice: "学徒",
    CharacterApprentices: "学徒",
    CharacterChild: "子女",
    CharacterChildren: "子女",
    CharacterMate: "配偶",
    CharacterMates: "配偶",
    CharacterMentor: "导师",
    CharacterMentors: "导师",
    CharacterParent: "父母",
    CharacterParents: "父母",
    ContributeToTheDataSource: "为数据源添砖加瓦",
    DurationMoon: "个月",
    DurationMoons: "个月",
    DurationYear: "年",
    DurationYears: "年",
    EmbedAppMenu: "点击以查看更多操作",
    EmbedPoweredBy1: "由{0}强力驱动",
    EntityNotFound1: "找不到关于此实体的更多信息：{0}。",
    EntityProfileTitle: "实体信息",
    EntitySearchBoxPlaceholder: "搜索角色…",
    FamilyTreeTitle: "家谱",
    FamilyTreeTitle1: "{0}家谱",
    GoToEntityDataSource: "跳转到此实体的数据源。",
    HoweverCheckout1: "但你仍可尝试在{0}找到一些内容。",
    InitializationDescription: "请稍后，我们仍在加载剩余的数据……",
    InitializationTitle: "正在初始化……",
    ListSeparator: "、",
    MissingTimelineInformation: "时间线信息缺失。",
    More: "更多",
    NamesTitle: "名字",
    NoFamilyTreeInformation: "无家谱信息。",
    OpenInNewWindow: "在新窗口打开",
    PageNeedsEntityId: "此页面需要实体ID作为参数。",
    PositionsHeldTitle: "职位",
    RelationsTitle: "亲属关系",
    SiteLinksTitle: "网站链接",
    StarTheRepo: "为我们点赞⭐",
    SwitchLanguage: "切换语言",
    TimelineUntilNow: "至今",
    UnknownValue: "未知",
    WelcomeDescription: "这是仍在施工中的《猫武士》自动家谱查看工具，请在下面的搜索框中输入一个角色名以继续。<br />例如：键入<b>火星</b>，然后按下回车键。",
    WelcomeTitle: "欢迎",
};

export default prompts;
