import { PromptsTable } from "./en";

const prompts: Partial<PromptsTable> = {
    AboutThisApp: "關於此應用",
    AboutThisAppDescription: "或者向我們提供反饋意見",
    Brackets: "（{0}）",
    CharacterApprentice: "見習生",
    CharacterApprentices: "見習生",
    CharacterChild: "子女",
    CharacterChildren: "子女",
    CharacterMate: "配偶",
    CharacterMates: "配偶",
    CharacterMentor: "導師",
    CharacterMentors: "導師",
    CharacterParent: "父母",
    CharacterParents: "父母",
    ContributeToTheDataSource: "為資料來源添磚加瓦",
    EmbedAppMenu: "點選以檢視更多操作",
    EmbedPoweredBy1: "由{0}強力驅動",
    EntityNotFound1: "找不到關於此實體的更多資訊：{0}。",
    EntityProfileTitle: "實體資訊",
    EntitySearchBoxPlaceholder: "搜尋角色…",
    FamilyTreeTitle: "家譜",
    FamilyTreeTitle1: "{0}家譜",
    GoToEntityDataSource: "跳轉到此實體的資料來源。",
    InitializationDescription: "請稍後，我們仍在載入剩餘的資料……",
    InitializationTitle: "正在初始化……",
    ListSeparator: "、",
    MissingTimelineInformation: "時間線資訊缺失。",
    NoFamilyTreeInformation1: "無家譜資訊。\n但你仍可嘗試在{0}頁面找到一些內容。",
    OpenInNewWindow: "在新視窗開啟",
    PageNeedsEntityId: "此頁面需要實體ID作為引數。",
    StarTheRepo: "為我們點贊⭐",
    SwitchLanguage: "切換語言",
    TimelineUntilNow: "至今",
    WelcomeDescription: "這是仍在施工中的《貓戰士》自動家譜檢視工具，請在下面的搜尋框中輸入一個角色名以繼續。<br />例如：鍵入<b>火星</b>，然後按下回車鍵。",
    WelcomeTitle: "歡迎",
};

export default prompts;
