name: App Deploy
on:
  push:
    tags:
      - v-*
    branches:
      - master
    paths-ignore:
      - '*.md'
  schedule:
    - cron: "12 3 * * SUN"

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 10
      - uses: actions/checkout@v3
        with:
          repository: crystal-pool/Dump
          fetch-depth: 2
          ref: master
      - name: PrepEnv
        shell: pwsh
        run: ./scripts/prepEnv.ps1
      - name: PrepSecrets
        shell: pwsh
        run: './scripts/BuildSecrets.ps1 -Restore -Key:"${{ secrets.BUILD_SECRET }}"'
      - name: PrepProject
        shell: pwsh
        run: ./scripts/prepProject.ps1
      - name: Build
        shell: pwsh
        run: ./scripts/build.ps1
      - name: Cleanup 1
        shell: pwsh
        run: './scripts/BuildSecrets.ps1 -Clear'
      - name: Deploy
        shell: pwsh
        run: ./scripts/deploy.ps1 -PublishingUser:"${{ secrets.DEPLOY_USER }}" -AuthPrefix:"${{ secrets.DEPLOY_AUTH }}"
